exclude: ^(src/blib2to3/|profiling/|unit_tests/data/)

repos:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: "https://github.com/psf/black"
    rev: "20.8b1"
    hooks:
      - id: "black"
        name: "Format code (black)"
        language_version: "python3"
  - repo: "https://github.com/asottile/blacken-docs"
    rev: "v1.9.2"
    hooks:
      - id: "blacken-docs"
        name: "Format docs (blacken-docs)"
        language_version: "python3"
        args: [ "-l", "64" ]
        additional_dependencies:
          - "black==20.8b1"
  - repo: "https://github.com/timothycrosley/isort"
    rev: 5.7.0
    hooks:
      - id: isort
        language_version: "python3"
        additional_dependencies: [ toml ]

