version: "3.8"
services:
  centos7int:
    user: root
    build:
      context: .
      dockerfile: Dockerfiles/integration.centos7.Dockerfile
    volumes:
    - ./.rpms:/data/.rpms
  centos8int:
    extends:
      service: centos7int
    build:
      dockerfile: Dockerfiles/integration.centos8.Dockerfile
  test-runner:
    build:
      context: .
      dockerfile: Dockerfiles/testrunner.Dockerfile
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/kvm:/usr/bin/kvm
    - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
    - ./convert2rhel:/convert2rhel/convert2rhel
    - ./.rpms:/convert2rhel/.rpms
    - ./tests:/convert2rhel/tests
    - ./plans:/convert2rhel/plans
